version: '3.8'

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - mynetwork
    ports:
      - "9000:9000" # Exposing port for PHP-FPM

  # Composer Service
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/var/www
    working_dir: /var/www
    networks:
      - mynetwork
    command: ["install", "--no-progress", "--prefer-dist"]

  # Neo4j Service (Optional, if you need Neo4j)
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"   # Web interface
      - "7687:7687"   # Bolt protocol
    networks:
      - mynetwork

# Define a network for communication between containers
networks:
  mynetwork:
    driver: bridge
