version: '3.8'

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    environment:
      # Change the password here as desired
      NEO4J_AUTH: "neo4j/your_password"
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
