name: PHP Tests

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    services:
      neo4j:
        image: neo4j:latest
        ports:
          - 7474:7474
          - 7687:7687
        env:
          NEO4J_AUTH: neo4j/password
        options: >-
          --health-cmd "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"
          --health-interval 10s
          --health-retries 5
          --health-timeout 5s

    name: Run PHPUnit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer, xdebug

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run Tests without phpunit.xml
        env:
          NEO4J_ADDRESS: "http://localhost:7474"
          NEO4J_USERNAME: "neo4j"
          NEO4J_PASSWORD: "password"
        run: vendor/bin/phpunit --configuration phpunit.coverage.xml ./tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage.xml
          fail_ci_if_error: true
          verbose: true
